sut:
  build: .
  command: echo "build complete"

test:
  build: .
  command: bash /universc/test/test_call.sh

test_10x:
  build: .
  command: bash /universc/test/run_tests_10x_local.sh

test_dropseq:
  build: .
  command: bash /universc/test/run_tests_dropseq_local.sh

test_icell8:
  build: .
  command: bash /universc/test/run_tests_icell8_local.sh
