name: Docker build image
on: push
jobs:
  test-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: clean environment
        run: rm -rf tests whitelist sub
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          registry: ${{ env.REGISTRY }}
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Status
        run: echo "build complete" 
      - name: Hello world
        run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest echo "hello world"


  test-call:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: clean environment
        run: rm -rf test whitelist sub 
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          registry: ${{ env.REGISTRY }}
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Status
        run: echo "build complete" 
      - name: Call functions
        run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}universc:latest git pull origin master && bash /universc/test/test_call.sh

