name: Test ICELL8
on: push
jobs:
  test:
    runs-on: tomkellygenetics/cellranger_clean:3.0.2.9001
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Status
        run: echo "build complete" 
      - name: Test runnning on ICELL8
        run:  test/run_tests_icell8.sh
