name: CI to Docker hub runners
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: ${{ env.REGISTRY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest
        push: false

  run:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: ${{ env.REGISTRY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest
        push: false
    - name: Hello world 
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest echo "hello world"
    - name: Repo diagnostics
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest pwd;ls
    - name: Repo size
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest pwd; du -sckh *
    - name: Parent directory diagnostics
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest pwd;ls ..
    - name: Parent directory size
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest pwd; du -sckh ../*
    - name: Root directory diagnostics
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest pwd;ls /*
    - name: Root directory size
      run: docker run ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest pwd; du -sckh /*
