name: CI to Docker hub
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:

      -

        name: Login to DockerHub

        uses: docker/login-action@v1 

        with:

          username: ${{ secrets.DOCKER_HUB_USERNAME }}

          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      -

        name: Build and push

        id: docker_build

        uses: docker/build-push-action@v2

        with:

          context: ./

          file: ./Dockerfile

          push: true

          tags: tomkellygenetics/universc:latest

      -

        name: Image digest

        run: echo ${{ steps.docker_build.outputs.digest }}
