name: Test 10x Genomics
on: push
jobs:
  login:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        registry: ${{ env.REGISTRY }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/universc:latest
        push: false
    - name: Run image
      run: docker run -it -d --name builder -v $GITHUB_WORKSPACE:/workspace -w tomkellygenetics/universc:1.0.2 echo "hello from universc"
    - name: Call UniverSC
      uses: addnab/docker-run-action@v1
      with:
        image: tomkellygenetics/universc:latest
        run: bash /universc/test/test_call.sh
    - name: Run image
      run: docker run -it -d --name builder -v $GITHUB_WORKSPACE:/workspace -w tomkellygenetics/universc:1.0.2 bash /universc/test/run_tests_10x.sh
    - name: Call UniverSC
      uses: addnab/docker-run-action@v1
      with:
        image: tomkellygenetics/universc:latest
        run: bash /universc/test/run_tests_10x.sh

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Status
        run: echo "build complete" 
      - name: Test runnning on 10x
        run:  test/run_tests_10x.sh
